server:
  port: 8080

logging:
  level:
    root: warn
    org.springframework.web: info
    org.springframework.security: info

spring:
  thymeleaf:
    cache: false
  profiles:
    active: test

#  security:
#    user:
#      name: root
#      password: root
